# Project: v2.1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mensajeria.o
LINKOBJ  = mensajeria.o
LIBS     = -L"Z:/Programas/Dev-Cpp/MinGW64/lib" -L"Z:/Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"Z:/Programas/Dev-Cpp/MinGW64/include" -I"Z:/Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"Z:/Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"Z:/Programas/Dev-Cpp/MinGW64/include" -I"Z:/Programas/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"Z:/Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"Z:/Programas/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = v2.1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mensajeria.o: mensajeria.cpp
	$(CPP) -c mensajeria.cpp -o mensajeria.o $(CXXFLAGS)
